js/adyen/payment/cc.js

After installation of the adyen module, our javascript at the checkout page was broken. 
We dit some research and the problem only appears when the js merging of Magento was on. After looking in the javascript files, we discovered a syntax error in the cc.js file.

[BUGFIX] Update comment syntac in cc.js

---

app/code/community/Adyen/Payment/Helper/Data.php
app/code/community/Adyen/Payment/Model/Adyen/Hpp.php
app/code/community/Adyen/Payment/Model/Adyen/Openinvoice.php
app/code/community/Adyen/Payment/Model/Adyen/PayByMail.php
app/code/community/Adyen/Payment/Model/Adyen/Pos.php

This way it is clear to everyone that this file in the log dir belongs to the adyen module

Rename http-request.log to adyen_http-request.log

---

app/design/frontend/base/default/layout/adyen.xml

Fixes missing closing ) of Javascript function

Fixes missing closing ) of Javascript function

---

app/code/community/Adyen/Payment/Helper/Pci.php

Revert "PHP 5.3 compatibility for arrays"

---

app/design/frontend/base/default/template/adyen/form/cc.phtml

Fixes #377 Javascript error in Multishipping checkout page 

---

app/code/community/Adyen/Payment/Model/ProcessNotification.php
app/code/community/Adyen/Payment/etc/config.xml
app/code/community/Adyen/Payment/etc/system.xml

This new functionalty breaks current logic in our webshops.
So there for we want to have this configurable.

[develop] +: making uncancelorder logic configurable.

---

app/code/community/Adyen/Payment/Model/Adyen/Data/PaymentRequest.php
app/code/community/Adyen/Payment/Model/Adyen/Hpp.php
app/code/community/Adyen/Payment/Model/Billing/Agreement.php
shell/adyen.php

Ps. I can't seem to create the pullrequest on the develop branch, seems they have diverged quite a bit, maybe cherry pick it your self.

Solve issue where customer increment ID is not used when available.

---

skin/frontend/base/default/css/adyenstyle.css

Please check issue #516
https://github.com/Adyen/magento/issues/516

Update adyenstyle.css to fix issue #516

---

app/code/community/Adyen/Payment/Model/Observer.php
app/code/community/Adyen/Payment/etc/config.xml
app/code/community/Adyen/Payment/etc/system.xml

By default is active as befoer

Option to disable auto refund on order cancel

---

app/code/community/Adyen/Payment/Model/Adyen/Openinvoice.php

Fixed typo in function of Openinvoice.php

---

app/code/community/Adyen/Payment/Model/ProcessNotification.php
app/code/community/Adyen/Payment/etc/config.xml
app/code/community/Adyen/Payment/sql/adyen_setup/mysql4-upgrade-2.5.4-2.5.4.1.php

We're integrating Riskified fraud detection system for one of our clients and we realized current module doesn't manage cardBin in notification processing

save cardBin on payment

---

app/design/frontend/base/default/template/adyen/form/openinvoice.phtml
app/design/frontend/base/default/template/adyen/widget/dob.php

Fixing conflicting validation checks with customer date-of-birth in onepagecheckout
Same as https://github.com/Adyen/magento/pull/592 but now, as requested, in develop branch.

Adding a seperate template for date-of-birth openinvoice validation checks.

---

app/code/community/Adyen/Fee/Model/Tax/Config.php

fixed call to non-existant method

---

app/code/community/Adyen/Payment/Model/Adyen/Cc.php
app/code/community/Adyen/Payment/Model/Adyen/Hpp.php

don't use $quote if it is null.
fixes Adyen/magento#620

fixes billing agreement page crash if cart is empty

---

app/code/community/Adyen/Payment/Block/Adminhtml/Sales/Order/Filter/Adyen.php
app/code/community/Adyen/Payment/Model/Event.php

Status (TRUE/FALSE) added to NOTIFICATION_OF_FRAUD and
NOTIFICATION_OF_CHARGEBACK items for the Sales/Order filter drop-down

Status (TRUE/FALSE) added to NOTIFICATION_OF_ items

---

app/design/frontend/base/default/template/adyen/form/oneclick.phtml

When a customer has several oneclick payment options displayed on the same page we get a issue with javascript functions being overwritten resulting in that only the "last" card in the dom actually working.
The encryption works for all cards but the data is added to the last card resulting in errors.

fix for javascript function overwrites (multiple oneclick payments)

---

app/code/community/Adyen/Payment/Model/Adyen/Hpp.php
app/code/community/Adyen/Payment/Model/ProcessNotification.php

Fixes https://github.com/Adyen/adyen-magento/issues/699

Fixed #699, Skip KCP notifications of zero amounts

---

app/code/community/Adyen/Fee/etc/config.xml

Fixes the issue raised in #711.

Remove superfluous characters in the Adyen Fee config.xml file

---

shell/adyen.php

filters by customer created date and storeid
`$ php adyen.php --action loadBillingAgreements --store 1 --createdAfter 2017-02-05`
resolves #730

[FEATURE] add filters for adyen BA loading shell script

---

app/code/community/Adyen/Payment/controllers/CheckoutCashController.php

Before //frontend etc
After /frontend etc

Remove double slash in path

---

app/code/community/Adyen/Payment/Model/Adyen/Abstract.php
app/code/community/Adyen/Payment/Model/Observer.php

Changed the action of the cancel button to do a cancellation rather than a cancel_or_refund

---

app/code/community/Adyen/Payment/Model/ProcessNotification.php
app/code/community/Adyen/Payment/etc/config.xml
app/code/community/Adyen/Payment/etc/system.xml

Disabled by default to prevent unexpected behavior

add a feature flag around the unholding

---

app/code/community/Adyen/Payment/etc/config.xml

* prepare version bump for composer

Version bump to 2.9.4

---

app/code/community/Adyen/Fee/etc/config.xml

* silly me to forgot about this

Also bumped Adyen/Fee

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

Added github templates for issues and PRs (https://github.com/blog/2111-issue-and-pull-request-templates)

Added github templates for issues and PRs

---

README.md

Format it as a list, it's more readable this way.

Format instruction/documentation links in README.md

---

app/code/community/Adyen/Payment/Block/ApplePay.php

Fix ApplePay subtotal calculation
ApplePay payment amount calculation

Bugfix for Applepay subtotal calculation

---

app/design/frontend/base/default/layout/adyen.xml
app/design/frontend/base/default/template/adyen/checkout/success.phtml

Success page added before continue shopping button.
First check if payment method is boleto and then display the div.
Make purchase with boleto payment method.
**Fixed issue**: 
N/A

Improvements

---

app/code/community/Adyen/Payment/controllers/ProcessController.php

Prevent duplicate HPP redirects
HPP flow: authorised/cancellation, revisit /redirect

Prevent duplicate HPP redirects

---

app/code/community/Adyen/Payment/Model/Adyen/Data/PaymentRequest.php
app/design/adminhtml/default/default/template/adyen/info/pay_by_mail.phtml

In API houseNumberOrName can be empty and number can be in address and 
fixed Notice: Undefined offset // pay_by_mail.phtml on line 50
All card flows
**Fixed issue**:  
Fix avs issues and #861

PW-328 Fix avs

---

app/code/community/Adyen/Payment/Model/Cronjob.php

fix little type error

---

app/code/community/Adyen/Payment/Model/ProcessNotification.php

OFFER_CLOSED notification able to Cancel order when status is Payment Review.
Closed browser before redirecting to 3D Secure page. 
Send OFFER_CLOSED notification for that order. 
Process OFFER_CLOSED notification.
Order status updated to Canceled.

Offer Closed

---

app/code/community/Adyen/Payment/Model/Adyen/Boleto.php
app/code/community/Adyen/Payment/Model/Adyen/Hpp.php
app/code/community/Adyen/Payment/Model/Adyen/Pos.php
app/code/community/Adyen/Payment/Model/Adyen/Sepa.php

Missing return statement
Purchases with payment methods: Sepa, Boleto, Pos, Hpp.
N/A

Missing return statement

---

app/code/community/Adyen/Payment/Block/Adminhtml/Notifications.php
app/code/community/Adyen/Payment/Helper/Data.php
app/code/community/Adyen/Payment/Model/ProcessNotification.php
app/code/community/Adyen/Payment/controllers/ProcessController.php
app/design/adminhtml/default/default/layout/adyen.xml
app/design/adminhtml/default/default/template/adyen/payment/notifications.phtml

Admin message is displayed if there are unprocessed notifications queued after first login.
Further the number of unprocessed notifications are shown in CA when sending a Test Notification to endpoint. 
Number of unprocessed notifications in Admin message and Test notification

PW-267 Cron health checks

---

app/code/community/Adyen/Payment/Model/Billing/Agreement/Observer.php
app/code/community/Adyen/Payment/Model/Observer.php

Use default null for observers parameters

Use default null for observers parameters

---

app/code/community/Adyen/Payment/Model/ValidateResultUrl.php
app/code/community/Adyen/Payment/controllers/ProcessController.php

Added extra information for RedirectShopper and Pending status
When shopper redirected to 3D Secure page, extra info in comments history
When Pending result, extra information for BankTransfer, Sepa, and other

Additional information in Comments history

---

app/code/community/Adyen/Payment/Helper/Data.php

Klarna_account needs to go to manual capture by default

Fix that klarna_account goes to manual capture by default

---

app/code/community/Adyen/Payment/Helper/Payment/Data.php
app/code/community/Adyen/Payment/etc/config.xml

revert #858

---

app/code/community/Adyen/Payment/Model/Adyen/Data/PaymentRequest.php

Keep cse token in session to be used for multi-shipping
Checkout CC + APM
Multishipping checkout using oneclick (cse)

Keep cse token in session to be used for multi-shipping

---

app/design/adminhtml/default/default/template/adyen/info/sepa.phtml
shell/adyen.php

fix to use array() instead of [] to pass Technical Report

---

js/adyen/payment/cc.js

Added new BINs to the credit card check.
Tested ELO cards
**Fixed issue**:  #751

Updated BIN card detection. Fixes #751

---

app/code/community/Adyen/Payment/etc/config.xml

Added amscheckoutfront to config.xml file

Added controller to config.xml file

---

js/adyen/payment/cc.js

Removed invalid js comment from cc.js

Removed comment, fixes #909

---

app/code/community/Adyen/Payment/Model/Adyen/Abstract.php

#904 get the right storeId for backend to provide the right url

---

README.md

PW-556 update readme

---

app/code/community/Adyen/Payment/Helper/Payment.php
app/code/community/Adyen/Payment/Model/Adyen/PayByMail.php
app/code/community/Adyen/Payment/etc/system.xml

Add payment flow selection for Pay By Mail method, previously the link was created only with One Page Payment Flow.
Backend paybymail orders, one page/multi page

PW-586: Add flow selection for Pay By Mail method

---

app/code/community/Adyen/Payment/Block/Form/PosCloud.php
app/code/community/Adyen/Payment/Block/Info/PosCloud.php
app/code/community/Adyen/Payment/Model/Adyen/PosCloud.php
app/code/community/Adyen/Payment/etc/config.xml
app/code/community/Adyen/Payment/etc/system.xml
app/design/adminhtml/default/default/template/adyen/form/pos_cloud.phtml
app/design/adminhtml/default/default/template/adyen/info/pos_cloud.phtml
app/design/adminhtml/default/default/template/adyen/pdf/pos_cloud.phtml
app/design/frontend/base/default/template/adyen/form/pos_cloud.phtml
app/design/frontend/base/default/template/adyen/info/pos_cloud.phtml
skin/frontend/base/default/css/adyenstyle.css

Added new payment method Adyen_PosCloud
Payment method and icon appear on frontend/backend

PW-596: Add cloud pos payment method

---

app/code/community/Adyen/Payment/controllers/ApplePayController.php

Set customer's email on quote level from ApplePay shippingContact in case of paying with ApplePay as not logged in user

Set customer's email on quote level from ApplePay shippingContact

---

app/code/community/Adyen/Payment/Helper/Data.php
app/code/community/Adyen/Payment/controllers/PosController.php
app/code/community/Adyen/Payment/etc/config.xml
app/design/adminhtml/default/default/template/adyen/info/pos_cloud.phtml
app/design/frontend/base/default/template/adyen/form/pos_cloud.phtml
app/design/frontend/base/default/template/adyen/info/pos_cloud.phtml

Parse Payment receipt from TerminalAPI PaymentResponse
Added 120 seconds timeout from Initiate call.
Formatting fixes.
Frontend order info, adminhtml order info.
Shopper email

PW-655 Parse Payment receipt from TerminalAPI PaymentResponse

---

app/code/community/Adyen/Payment/Model/Api.php
app/code/community/Adyen/Payment/etc/system.xml

Update Secure fields to support dynamic checkout endpoint.
Added comment and tooltip in the configuration page to explain which part of the URL needs to be filled in.

PW-646: Update Secure fields to support dynamic checkout endpoint

---

app/code/community/Adyen/Payment/Model/Api.php

Use demo/live configuration from store when doing listRecurringDetails and creating Billing Agreements

Use demo/live configuration from store when doing listRecurringDetails

---

app/code/community/Adyen/Payment/Model/Adyen/Data/ApplicationInfo.php
app/code/community/Adyen/Payment/Model/Adyen/Data/ModificationRequest.php
app/code/community/Adyen/Payment/Model/Adyen/Data/PaymentRequest.php
app/code/community/Adyen/Payment/Model/Adyen/Data/PaymentRequest3d.php
app/code/community/Adyen/Payment/etc/Payment.wsdl

Add applicationInformation into M1
Authorise
Modifications
Authorise3D

PW-564: Updated WSDL to v40, added applicationInfo

---

app/code/community/Adyen/Payment/Model/Adyen/Data/PaymentRequest.php

Assign default value to address fields when not supplied in API

---

app/design/frontend/base/default/template/adyen/form/cc.phtml

Translate strings

---

app/design/frontend/base/default/template/adyen/form/cc.phtml
app/design/frontend/base/default/template/adyen/form/oneclick.phtml

Added frontend validation for securedfields

---

app/design/adminhtml/default/default/template/adyen/form/cc.phtml
app/design/adminhtml/default/default/template/adyen/form/oneclick.phtml
app/design/frontend/base/default/template/adyen/form/oneclick.phtml

Make labels translatable

---

app/code/community/Adyen/Payment/Block/Adminhtml/Sales/Billing/Agreement/Grid.php

PR for issue: https://github.com/Adyen/adyen-magento/issues/870

Adding escaping for name field

---

app/code/community/Adyen/Payment/etc/config.xml

Adding China Union Pay to card options in Magento

PW-1167 add cup

---

app/design/adminhtml/default/default/template/adyen/form/cc.phtml

Removing unnecessary div, fixes #983

---

app/code/community/Adyen/Payment/Model/ProcessNotification.php

**Fixed issue**:  alphanumeric psp references were treated as TEST notifications

PW-1309: fix for alphanumeric pspreferences

---

app/code/community/Adyen/Payment/Helper/Data.php
app/design/adminhtml/default/default/template/adyen/form/cc.phtml
app/design/frontend/base/default/template/adyen/form/cc.phtml
app/design/frontend/base/default/template/adyen/form/oneclick.phtml
skin/adminhtml/default/default/adyencheckout.css
skin/frontend/base/default/css/adyencheckout.css

Updated checkout components to version 3.0.0
Updated css files with new ones from version 3.0.0

PW-1367: Update components version to 3.0.0

---

app/code/community/Adyen/Payment/Model/Api.php

Add port into origin key retrieval
Use getOrigin instead of duplicate code

PW-1404 Generate origin key for urls with port

---

app/code/community/Adyen/Payment/etc/config.xml
app/design/frontend/base/default/template/adyen/threeds2.phtml

Challenge should be full screen and enabled by default

---

app/design/frontend/base/default/template/adyen/form/cc.phtml

`<ul>` elements only must contain `<li>` elements, not `<div>` elements.

Fix HTML error

---

app/design/frontend/base/default/layout/adyen.xml

Add threeds2-js-utils.js script for custom checkouts and multishipping

PW-1655: Add threeds2-js-utils.js to adyen.xml fixes #1044

---

app/code/community/Adyen/Payment/Model/Api.php

PW-1669: Add missing constant

---

README.md
app/code/community/Adyen/Payment/Block/Adminhtml/Notifications.php
app/code/community/Adyen/Payment/etc/system.xml

fixed broken links on magento backend and readme

PW-1557: fix broken docs links in configuration and Readme

---

app/code/community/Adyen/Payment/Helper/Data.php
app/code/community/Adyen/Payment/Model/Adyen/Data/ApplicationInfo.php
app/code/community/Adyen/Payment/Model/Api.php
app/code/community/Adyen/Payment/controllers/PosController.php

[PW-2023] Add merchantApplication into API calls

---

app/code/community/Adyen/Fee/etc/config.xml
app/code/community/Adyen/Payment/Helper/Data.php
app/code/community/Adyen/Payment/Model/Adyen/Data/ApplicationInfo.php
app/code/community/Adyen/Payment/Model/Api.php
app/code/community/Adyen/Payment/controllers/PosController.php
app/code/community/Adyen/Payment/etc/config.xml

Release 2.18.2

---

app/design/frontend/base/default/template/adyen/apple_pay.phtml

Use shipping information for Apple Pay

---

app/code/community/Adyen/Payment/Model/Adyen/Oneclick.php
app/code/community/Adyen/Payment/etc/system.xml

PW-2319: add “Disable at zero grand total” for adyen_oneclick

---

app/code/community/Adyen/Payment/Helper/Payment.php
app/code/community/Adyen/Payment/Model/Api.php

Send openinvoice lines for pay by link
Klarna DE

PW-2395: Send openinvoice lines for /v52/paymentlinks

---

app/code/community/Adyen/Fee/etc/config.xml
app/code/community/Adyen/Payment/Helper/Payment.php
app/code/community/Adyen/Payment/Model/Api.php
app/code/community/Adyen/Payment/etc/config.xml

#1092 send Openinvoice lines for /paymentLinks

Release 2.18.5
