Adyen/adyen-magento

- app/code/community/Adyen/Payment/Block/Form/Boleto.php
- app/code/community/Adyen/Payment/Block/Form/Cc.php
- app/code/community/Adyen/Payment/Block/Form/Elv.php
- app/code/community/Adyen/Payment/Block/Form/Openinvoice.php
- app/code/community/Adyen/Payment/Block/Form/Pos.php
- app/code/community/Adyen/Payment/Block/Form/Sepa.php
- app/design/frontend/base/default/template/adyen/form/cc.phtml
- app/design/frontend/base/default/template/adyen/form/hpp.phtml
- app/design/frontend/base/default/template/adyen/form/oneclick.phtml
- app/design/frontend/base/default/template/adyen/saved_cards.phtml
Magento returns invalid url if backslashes are found within file path:
The generated url is not correct and don't works:
```
example.com/skin/frontend/base/default/images\adyen\ae_small.png
```
This fix removes this issue.
P.S. I found that [you are using](https://github.com/adyenpayments/magento/blob/develop-2.3.0/app/design/frontend/base/default/template/adyen/form/hpp.phtml#L94) `DS` as value separator in inputs. I don't think you did that purposely, or am I wrong?
> getSkinUrl method accept path with slashes only

- composer.json
I've removed the "magento-hackathon/magento-composer-installer" requirement from the composer.json.
Adyen does not actually relies on this module.
This requirement causes issue's if you use something else then the hackathon method or (in my case) use a newer version (dev-master) of the hackathon module.
> Removed requirement for magento-hackathon/magento-composer-installer.

- app/code/community/Adyen/Payment/Helper/Pci.php
- app/code/community/Adyen/Payment/Model/Adyen/Abstract.php
- app/code/community/Adyen/Payment/Model/Adyen/Data/Abstract.php
Currently PCI sensitive data (credit card details) are logged to disk.
This commit obscures PCI sensitive data before it is written to log
files.
> Obscure PCI sensitive data in logs

- app/code/community/Adyen/Payment/Model/Adyen/Abstract.php
When running Magento on HHVM I get the following error:
```
SOAP_ERROR: Invalid 'encoding' option - '2'
```
This is due to an error when the SOAP Client is instantiated.
The encoding option accepts a string identifier of the encoding, eg. 'UTF-8', 'ISO-8859-1'. Soap messages as always sent as UTF-8, this options is used to convert strings before sending the soap request.
To use SOAP requests with what is called literal encoding the "use" option should be set to SOAP_LITERAL.
> Fixed SoapClient param error.

- app/code/community/Adyen/Payment/controllers/ProcessController.php
We had some issues running the adyen magento module on a Nginx server with PHP-FPM.
To fix an exception about duplicate header 'Content-Type' I added a clearHeader('Content-Type') before setting the new Content-Type. This fixes the issue.
> Content-Type headers need to be cleared for use with php-fpm / nginx.

- app/code/community/Adyen/Payment/Helper/Pci.php
PHP 5.3 compatibility for Older Magento versions which don't support php 5.4+
> PHP 5.3 compatibility for arrays

- app/code/community/Adyen/Payment/controllers/Adminhtml/Adyen/Event/QueueController.php
- app/code/community/Adyen/Payment/controllers/Adminhtml/ExportAdyenSettingsController.php
- app/code/community/Adyen/Payment/controllers/Adminhtml/ValidateWebserverSettingsController.php
Added missing "_isAllowed" functions. These functions are required after applying Magento's SUPEE-6285 patch for accessing Admin controllers with custom ACL.
> [TASK] Implement _isAllowed required by SUPEE-6285

- app/code/community/Adyen/Payment/Model/Authenticate.php
- app/code/community/Adyen/Payment/etc/system.xml
This option disables the check on merchant account when notifications are
received. This makes it possible to use multiple merchant accounts in one
magento environment. (one merchant account per website for instance)
> "Allow multiple merchants" option in adyen payment method default settings

- app/design/adminhtml/default/default/template/adyen/form/sepa.phtml
This way, the SEPA info is remembered when creating an order in the backend, for instance when selecting another shipping method.
> +: Save SEPA info in localStorage

- app/code/community/Adyen/Payment/Model/Billing/Agreement.php
We don't always want to add the reference ID to the method code of a billing request, for example when adding our own payment method to work with billing agreements.
> B: Only add referenceId to method code when method is adyen_oneclick

- app/code/community/Adyen/Payment/Model/ProcessNotification.php
Added an extra condition to compare` $this->_success` to an empty string. It can be an empty string because in `_declareVariables` method it is set as: `$this->_success = trim($params->getData('success'));` If `$params->getData('success')` is `false` (boolean false) as in my case, then `trim(false)` will result in an empty string.
This is not an issue elsewhere in the code as we build the condition to check if success is true or 1 which always works.
> Fixes #426 with wrong "success" flag validation.

- app/code/community/Adyen/Payment/Model/Adyen/Data/Classmap.php
I don't know if this breaks something else, but when using manual capture I get the error "Class Undefined" when I do capture on-line on the order.
The problem seems to be from [Model/Adyen/Abstract.php](https://github.com/Adyen/magento/blob/develop/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php#L287)
```php
case "capture":
$response = $this->_service->capture(array(
'modificationRequest' => $requestData,
'modificationResult' => $modificationResult));
break;
```
where the array keys are camelCase and not found in the Classmap.
When I changed the `Classmap` properties to camelCase it worked as expected. 
I don't know if this change breaks something else though.
> Class map should be camelCase. Fixes error when using manual capture

- app/code/community/Adyen/Payment/controllers/ProcessController.php
- app/locale/de_DE/Adyen_Payment.csv
- app/locale/es_ES/Adyen_Payment.csv
- app/locale/fr_FR/Adyen_Payment.csv
- app/locale/nl_NL/Adyen_Payment.csv
AfterPay has the requirement that in case of an error a text like this will be shown to the customer:
`Het spijt ons u te moeten mededelen dat uw aanvraag om uw bestelling achteraf te betalen op dit moment niet door AfterPay wordt geaccepteerd. Dit kan om diverse (tijdelijke) redenen zijn. Voor vragen over uw afwijzing kunt u contact opnemen met de Klantenservice van AfterPay. Of kijk op de website van AfterPay bij 'Veel gestelde vragen' via de link http://www.afterpay.nl/page/consument-faq onder het kopje 'Gegevenscontrole'. Wij adviseren u voor een andere betaalmethode te kiezen om alsnog de betaling van uw bestelling af te ronden.`
With this adjustment the error message for the open invoice payment method can be translated separately from the normal error message.
> If an openinvoice payment failed, we need to show a different error message to the customer.

- app/design/adminhtml/default/default/layout/adyen.xml
When sales_flat_order_payment is joined on the order grid you cannot filter on adyen_event_code anymore and this error is thrown:
Integrity constraint violation: 1052 Column 'adyen_event_code' in where clause is ambiguous
The filter_index solves this.
> Add a filter index to prevent ambiguous columns

- app/code/community/Adyen/Payment/Model/Adyen/Openinvoice.php
`$adyFields['shopper.infix']` is optional after https://github.com/Adyen/magento/commit/a1bd8775ff5874e4dd59f3cf43d4cd1a807e2058
```
Notice: Undefined index: shopper.infix in /var/www/vhosts/coltex/httpdocs/app/code/community/Adyen/Payment/Model/Adyen/Openinvoice.php on line 312
```
> Bugfix: undefined index: shopper.infix

- app/code/community/Adyen/Payment/Model/Api.php
- app/design/frontend/base/default/template/adyen/form/cc.phtml
Composer.json does not have a php version contraint, so it would be a shame to break the backward compatibility just for array notation.
> Don't break backward compatibility with older PHP versions.

- app/code/community/Adyen/Payment/Model/ValidateResultUrl.php
First we get the message that the order payment where canceled, thats when we cancel the order.
Then we get the message that the order payment is succesful, then it tries to proccess the order.
Causing the order to come in a state, not able to do anything anymore with the order.
> +: first status cancel then succes issue with ideal.

- app/design/frontend/base/default/template/adyen/form/openinvoice.phtml
- app/design/frontend/base/default/template/adyen/widget/dob.phtml
We had a problem after adding date-of-birth in customer checkout, the validation of the date-of-birth widget in openinvoice failed. Adding a special Adyen template for date-of-birth widget used in openinvoice with another validation class. 
Martijn van der Hulst will contact you over this.
> Date-of-birth widget in openinvoice 

- app/code/community/Adyen/Fee/Model/Total/PaymentFee/Tax/Creditmemo.php
When checking without typecasting to float, a value (string) '0.000' will
be processed as true, which results in a 'Division by zero' error on line 36
> [OPPO-1191] B: Prevent division by zero

- app/code/community/Adyen/Payment/Model/Adyen/Openinvoice.php
Generated Hmac key was invalid when a newline existed in a product name.
(just trim wasn't enough since the problem also occured when a newline was in
the middle of the product name)
> Trim whitespace and strip newlines from product name

- app/code/community/Adyen/Payment/Model/Adyen/Abstract.php
- app/code/community/Adyen/Payment/Model/Adyen/Data/ModificationRequest.php
- app/code/community/Adyen/Payment/Model/Observer.php
- app/code/community/Adyen/Payment/etc/config.xml
Fixes issue #457.
Get the same currency as the order was made in when doing a capture / refund i.e use getGrandTotal of the invoice/creditmemo instead using getBaseGrandTotal.
> Fixed problem with capture and creditmemo when using different currencies.

- app/code/community/Adyen/Payment/etc/config.xml
- app/code/community/Adyen/Payment/etc/system.xml
- app/design/frontend/base/default/layout/adyen.xml
when shop has advanced shipping options in checkout it might be wise to force user
through checkout instead of direct payment
> [TASK] add configuration to hide apple buy button on non-checkout pages

- app/code/community/Adyen/Payment/Model/Adyen/Pos.php
- app/code/community/Adyen/Payment/Model/Source/POS/IpFilter.php
- app/code/community/Adyen/Payment/etc/system.xml
The IP filter for POS payment method is only available by setting the IP range. 
However, sometime we need to set the discrete IP address, like 
"xx.xx.xx.xx,yyy.yyy.yyy.yyy"
This pull requests modify the "ip_filter" in system configuration, by adding one more method to set the IP whitelist.
> [add] specify multiple IPs for POS IP filter

- app/code/community/Adyen/Payment/Helper/Data.php
32bit PHP systems are incapable of representing a 128bit address (IPv6) in a 32bit integer (used by ip2long) so the current ipInRange method isn't compatible with IPv6 addresses.
This moves the ipInRange function over to using inet_pton, which represents the IP as a string instead (the in_addr representation of the given IP address). This function has been in PHP since 5.1.0 and has 7.x.x support, however on Windows systems it's only been compiled with the main binary since 5.3.0. This shouldn't be an issue since modern Magento distributions require PHP 5.4 as a minimum.
> Adding IPv6 support to IP filters

- app/design/adminhtml/default/default/template/adyen/form/cc.phtml
- app/design/adminhtml/default/default/template/adyen/form/oneclick.phtml
- app/design/frontend/base/default/template/adyen/form/cc.phtml
- app/design/frontend/base/default/template/adyen/form/oneclick.phtml
@rikterbeek's latest merge added validation as a form of forcing mobile browsers to use numeric keyboards. As long as we're adding validation (numbers only), we may as well use it properly and validate against 14+ character for CC numbers and 3+ for CVV numbers. I would have gone with 14-19 characters for the credit card, but with the space adding javascript it was a bit more complicated.
We could reasonably change this to `14,22` to accommodate for 14,19 characters + 3 spaces.
Further improvements to: #710.
> Credit card number length validation

- app/design/frontend/base/default/template/adyen/form/cc.phtml
On Safari, if an input field has the autocomplete="cc-number" attribute and is on a secure connection, then Safari will recognize it as an creditcard field and offer autocomplete and a card scanner.
> Allow safari users to scan credit cards

- app/code/community/Adyen/Payment/Helper/Payment.php
- app/code/community/Adyen/Payment/Model/Adyen/Data/PaymentRequest.php
- shell/adyen.php
Cause 
```
$customerReference = $customerData['adyen_customer_ref']
?: $customerData['increment_id']
?: $customerId;
```
would never have worked
> Fixed a malformed if else

- app/code/community/Adyen/Payment/Model/ProcessNotification.php
There is no reason to completely fail the process, specially since no orders are processed after
> Catch order errors when processing notifications

- app/code/community/Adyen/Payment/Model/ProcessNotification.php
Check for Hold state, unhold when it is. This will resolve the issue for the situation in the screenshot. First we get a cancelled notification and the order is pushed into the "Hold" state. When we later receive an authorisation notification this change will check if the order is on the hold state and unhold it first before creating the invoice.
> Check for Hold state, unhold when it is.

- app/code/community/Adyen/Payment/Model/ProcessNotification.php
- app/code/community/Adyen/Payment/controllers/ProcessController.php
1. Skip order cancellation if it's previously authorised
2. Consider an order fully paid if the authorised amount is at least the order's total amount
Tested HPP flow of authResult = CANCELLED and then authResult = AUTHORISED
> Skip order cancellation if it's previously authorised

- app/code/community/Adyen/Payment/data/adyen_setup/data-upgrade-2.9.4-2.9.4.1.php
- app/code/community/Adyen/Payment/etc/config.xml
Removed Magento country restriction for showing iDeal, so that it will show up as long as it is returned from directory lookup.
Checkout with NL, BE (ideal configured in skin), DE (ideal not configured)
> Remove Magento country restriction for showing iDeal

- app/code/community/Adyen/Payment/Model/ProcessNotification.php
When a credit memo is generated and contains the full refund, in Magento the State should be on CLOSED, the setData is the only way to force the State to be closed.
Full amount refund from the Backoffice
**Fixed issue**:  State was set on processing instead of closed
> Fix for setting the State to CLOSED after a Refund notification

- app/code/community/Adyen/Payment/Helper/Payment/Data.php
- app/code/community/Adyen/Payment/Model/Observer.php
- app/code/community/Adyen/Payment/etc/config.xml
Populate payment methods from payment helper.
Fixes interferences with 3rd party (checkout) modules and removes the observer invocation.
Frontend/backend payment
> Populate payment methods from payment helper

- app/code/community/Adyen/Payment/Helper/Payment/Data.php
In the function "addMethodsToConfig" the first parameter is expected to be a Varien_Event_Observer. In PHP 5 it is possible to pass null to this parameter. In PHP 7 this is not possible anymore.
Solution to this issue, Pass an empty Varien_Event_Observer as parameter since no where in the function is checked on null, no behavior will change.
**Fixed issue**:  Adyen Payment not compatible with PHP 7
> Adyen Payment PHP 7 compatibility

- app/code/community/Adyen/Payment/Helper/Payment.php
Do not send the deliveryAddress in the request if it is empty. For example for downloadable products there is no delivery address.
Shopping cart with only downloadable products -> deliveryAddress not set in request
Shopping cart with downloadable products and normal products -> deliveryAddress set in request
Shopping cart with only normal products -> deliveryAddress set in request
> Don't send deliveryAddress to HPP if it is not set

- app/code/community/Adyen/Payment/Model/ProcessNotification.php
Oneclick contract is not updated upon expiry date change, we need to do something similar to M2: https://github.com/Adyen/adyen-magento2/pull/172/files
Pay with oneclick card and change the expiry date
**Fixed issue**:  Fixes #896
> PW-417 Update expiry date in Magento when using ONECLICK payments

- app/code/community/Adyen/Payment/Model/Api.php
add try/catch to originkey call.
If api key is incorrect shopper is still able to pay with other payment methods
> catch exception on originkey call

- app/code/community/Adyen/Payment/Model/Adyen/Abstract.php
Line #240 in https://github.com/Adyen/adyen-magento/blob/master/app/code/community/Adyen/Payment/Model/Adyen/Abstract.php is cast to a bool, should be the date field of the base_zero_auth_on_date config.
> Remove bool type cast Zero auth date field

- app/code/community/Adyen/Payment/Model/ProcessNotification.php
A check was added in the past to not change holded orders. However,
the check was done with a non-existing order state (pending), while
this should have been pending_payment. This is replaced with the
constant defined by Magento itself.
When creating an order before this fix, while setting the value for the option "Order status: payment authorisation" to "Processing", the order would get the status "Processing" and when setting the state in the first step, the state will also be set to "Processing". Later in the process, when creating an invoice is created, it will be set to "Pending Payment", which should be changed back to "Processing" as soon as the payment is authorised. That didn't happen. This breaks the default Magento Sales Reports, as they …
> Fix incorrect order state from pending to pending payment

- app/code/community/Adyen/Payment/controllers/PosController.php
Resolves next issues experienced after upgrading to the latest version and activating / testing POS cloud payment method:
* Order increment ID registered to the Adyen transaction was incorrect when payment was canceled and re-attempted. Forcing regeneration of Magento order increment ID on each attempt resolves this.
* Upon quote save failure, the controller would just be halted, breaking the checkout flow. This is now handled gracefully, resulting in the failure being returned to frontend and logged to the Magento exception logs.
> POS cloud payment method improvements - regenerate order increment ID correctly and gracefully handle quote save exceptions

- app/code/community/Adyen/Payment/etc/system.xml
Makes sure the live api key gets Encrypted when saving it for the POS cloud payment method.
Tested scenarios
Tested on Magento 1.14.4.1 & Adyen 2.13.1
* Placing an order with 'POS Cloud' when the module is set to live mode 
-> validated if the api_live_key is set correctly on the request header
* Saving and updating the api key in the backend
**Fixed issue**:  #990
> Pos cloud backend configuration

- app/code/community/Adyen/Payment/Model/Api.php
When using 3d secure cards exception is thrown
`Exception: Notice: Undefined variable: storeId  in /vagrant/app/code/community/Adyen/Payment/Model/Api.php on line 384`
Tested using 3d secure cards, payment went through correctly
**Fixed issue**:  https://github.com/Adyen/adyen-magento/issues/1037
> Fix undefined storeId in 3d secure payments

- app/code/community/Adyen/Payment/Model/Adyen/Abstract.php
When using 3d secure cards exception is thrown
`Exception: Notice: Undefined index: pspReference in ./app/code/community/Adyen/Payment/Model/Adyen/Abstract.php on line 601 in`
Tested using 3d secure cards, payment went through correctly
> Fix undefined pspReference in 3d secure payments

- app/design/frontend/base/default/template/adyen/apple_pay.phtml
- app/design/frontend/base/default/template/adyen/threeds2.phtml
Replaces relative redirects for URLs such as 'checkout/onepage/success' with the actual secure URL. This resolves issues when store code is present in the url or when the actual checkout URL is different. 
Tested the 3ds case on 1.9.4.2 with store code and with a custom front name for onepage checkout.
**Fixed issue**:  #1050
> Properly redirect from 3ds and apple pay on frontend

- app/code/community/Adyen/Payment/Model/Adyen/Abstract.php
Paymentresult is the result of the old api, which is not used anymore
**Fixed issue**:  #1035
> Fix for undefined property paymentResult, fixes #1035

- app/code/community/Adyen/Payment/Model/ProcessNotification.php
Fixed inconsistent state when an order goes to Manual Review in Case Management. Orders stay in payment_review so they cannot be cancelled when a CANCEL_OR_REFUND notification is received.
* Place an order. The status state of that order must be payment_review (for example for us happens when using adyen_oneclick)
* Receive a notification with Manual Review
* State is still on pament_review, should be pending_payment
**Fixed issue**:  #1068
> Review fix

- app/code/community/Adyen/Payment/Model/Api.php
Remove the default value for address housenumberOrName 'N/A' for pay by link. Similar to payments the housenumberOrName default value is not requested
Do a pay by link cc transaction 
> Remove default housenumber or name paybylink

- app/code/community/Adyen/Payment/Model/ProcessNotification.php
- app/code/community/Adyen/Payment/Model/ProcessPaybylink.php
- app/code/community/Adyen/Payment/etc/config.xml
- app/code/community/Adyen/Payment/etc/system.xml
- Do not cancel paybylink orders on AUTHORISATION false and OFFER_CLOSED
- Make cron time for cancelling orders configurable(default 1 hour)
> PW-2511: do not cancel paybylink orders on AUTHORISATION false and OFFER_CLOSED, cron time configurable

- app/code/community/Adyen/Fee/etc/config.xml
- app/code/community/Adyen/Payment/Helper/Payment.php
- app/code/community/Adyen/Payment/Model/Api.php
- app/code/community/Adyen/Payment/Model/ProcessNotification.php
- app/code/community/Adyen/Payment/Model/ProcessPaybylink.php
- app/code/community/Adyen/Payment/etc/config.xml
- app/code/community/Adyen/Payment/etc/system.xml
_Pay By Link_ fixes: 
#1098 [PW-2521] Always send `houseNumberOrName` (N/A or parsed from the address field for required countries), added `taxCategory` **`High`** since it is required for Afterpay
#1099 [PW-2511] _Pay By Link_ orders are not cancelled anymore by `AUTHORISATION false `and `OFFER_CLOSED` notifications, added configuration to set the number of hours after the Pay By Link orders are automatically cancelled by a cronjob.
> Release 2.18.6
